
-- CREATE TABLE pacientes(
--     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     nome VARCHAR(100) NOT NULL,
--     data_nasc DATE NOT NULL,
--     ativo BOOLEAN NOT NULL,
--     usuario_alteracao VARCHAR(50) NOT NULL,
--     data_cadastro TIMESTAMP NOT NULL
-- );


-- CREATE TABLE historico(
--     id int GENERATED BY DEFAULT AS IDENTITY,
--     id_paciente int,
--     peso DECIMAL NOT NULL,
--     altura DECIMAL NOT NULL,
--     imc DECIMAL NOT NULL,
--     usuario_alteracao VARCHAR(50) NOT NULL,
--     data_alteracao TIMESTAMP,
--     FOREIGN KEY(id_paciente) REFERENCES pacientes (id)
-- );

-- INSERT INTO historico (id_paciente, peso, altura, imc, usuario_alteracao, data_alteracao)
-- VALUES
-- (1,105.2,2.02,20.0,'admin', CURRENT_TIMESTAMP);

-- INSERT INTO historico (id_paciente, peso, altura, imc, usuario_alteracao, data_alteracao)
-- VALUES
-- (3,69.1,1.7,21.3,'admin', CURRENT_TIMESTAMP);

-- DROP TABLE pacientes

-- INSERT INTO pacientes(nome, data_nasc, ativo, usuario_alteracao, data_cadastro) VALUES('Ricardo Alves Roberto', '1982-09-17', true, 'admin', CURRENT_TIMESTAMP);
-- INSERT INTO pacientes(nome, data_nasc, ativo, usuario_alteracao, data_cadastro) VALUES('Silvania da Silva Roberto', '1981-03-20', true, 'admin', CURRENT_TIMESTAMP);

SELECT * from pacientes;